riscv/riscv-v-spec

- listing.adoc
Change signatures that use `imm` (issue #25)
> Fix invalid signatures of immediates

- listing.adoc
- v-spec.adoc
Based on issue #30 , update the element and bit position notation in v-spec.adoc and listing.adoc
(while listing.adoc is not currently up-to-date, the notation should at least be consistent between the two files)
> Element and Bit Position Notation Update

- v-spec.adoc
- vector-op-types.csv
Some comments and clarifications in reference to issues #38 , #37 , #24  , #26
> Comments and clarifications regarding reductions, profiles, negations, etc.

- v-spec.adoc
This fixes a problem in the html output.
> Don't escape <= inside quotes.

- v-spec.adoc
Fixed "vwredsum.vv" to "vwredsum.vs" in section 15.2.
> Minor typo fix in section 15.2

- v-spec.adoc
I couldn't separate the commits. One was already applied.
> typo corrections

- vector-examples.adoc
Change a to ap, and likewise for b and c.
> Fix minor typos in sgemm example.

- inst-table.adoc
- mapping-lmul1.svg
- v-spec.adoc
- valu-format.adoc
- vamo-format.adoc
- vcfg-format.adoc
- vector-examples.adoc
- vmem-format.adoc
- vtype-format.adoc
Here is a resulted rendering:
Single page HTML: https://drom.io/vector/
PDF: https://drom.io/vector/vector.pdf
Build scripts is here: https://github.com/drom/datasheet-riscv
> formatted document for better HTML / PDF rendering

- v-spec.adoc
> Clarify that vsetvl resets vstart to 0, too

- inst-table.adoc
- v-spec.adoc
- vtype-format.adoc
> Converted "verbatim" to AsciiDoc tables where it is appropriate.

- v-spec.adoc
> vfwredosum.vs promotes inputs before adding

- inst-table.adoc
vfsgnxn => vfsgnjx
Signed-off-by: Weiwei Wang <weiwei.wangx@outlook.com>
> Fix typo of vfsgnjx

- v-spec.adoc
> Weaken constraint on VMADC overlap; apply new constraint to all comparisons

- v-spec.adoc
No normative changes are intended.
> Improve description of vfredsum/vfredosum instructions

- v-spec.adoc
> Sign-extend vmv.x.s and vmv.s.x

- v-spec.adoc
> strnlen should zero the tail elements

- v-spec.adoc
> Flesh out new vsetvl{i} proposal

- inst-table.adoc
- v-spec.adoc
This is my preferred resolution to #278.
> Add floating-point narrowing conversion with jamming

- v-spec.adoc
> Distinguish signed and unsigned roundoff functions

- v-spec.adoc
> Issue #220 State when on 5-bit immediate is sign extended to SEW or is unsigned 

- vector-examples.adoc
Also aligned first comment in loop
> Incorrect comment in code sample

- inst-table.adoc
- v-spec.adoc
> Add vfslide1up/down instructions

- inst-table.adoc
- v-spec.adoc
> Add FP->int truncating conversions

- vtype-format.adoc
As spotted by James Kenney
https://github.com/riscv/riscv-v-spec/commit/a5a62bd89de649744b65aef1be334bde0ae10ffd#commitcomment-38856359
> Fix off-by-one

- v-spec.adoc
Resolves #385.  (See #385 for explanation.)
> Refine choice of additive identity for vf[w]redsum

- v-spec.adoc
> Add assembly pseudoinstructions vncvt.x.x.v

- v-spec.adoc
> ordered --> unordered typo fix

- v-spec.adoc
Clarify immediate sign-/zero-extension
> Clarify immediate sign-/zero-extension

- vector-examples.adoc
Exchange two instructions in order to make the example correct.
> fix bug in Conditional example

- package.json
> fixes #584 ; `npm build` fails due to lack of pushd

- v-spec.adoc
> Fix minor typos

- v-spec.adoc
> Use new vmmv.v pseudoinstruction consistently

- v-spec.adoc
> Specify fault-only-first segment load exception behavior

- v-spec.adoc
> Add notes for vl=0 behavior of instructions that write scalars

- v-spec.adoc
Add element number in example for more clarity.
> Add element number in vcompress example

- example/strncpy.s
Reverts riscv/riscv-v-spec#728
Has bugs.
> Revert "Fix implementation of strncpy"

- fraclmul.adoc
- v-spec.adoc
Krste, 
Take a look if you like this fractional LMUL example Annex I added. I don't have a reference to it in the main text, pending to see if you approve this PR or not.
> Added Annex 'Fractional LMUL example'

- fraclmul.adoc
- v-spec.adoc
Reverts riscv/riscv-v-spec#736
> Revert "Revert "Added Annex 'Fractional LMUL example'""

- v-spec.adoc
This pull request implements the two suggestions outlined in #742, thus closes #742.
> Clarify Zve* extensions

- inst-table.adoc
This improves readability for users.
> Add funct6 to vmv<nr>r in inst-table

- v-spec.adoc
Two tables had an empty and unused last column since c32b714
Signed-off-by: Hugues de Lassus <hugues.delassus@sifive.com>
> Remove unused empty columns

- v-spec.adoc
Signed-off-by: Craig Topper <craig.topper@gmail.com>
> Clarify meaning of 'B' in vfrsqrt7 description

- v-spec.adoc
> Clarify Zicsr dependence
