riscv/riscv-v-spec

- v-spec.adoc
Spells out more details of the current proposal for double- and quad-word vector registers as explained by Krste in the meeting today.
> Clarify d/q register alignment and numbering gaps

- v-spec.adoc
As mentioned in #11, arithmetic instructions should also use 2vemaxw for d registers and 4vemaxw for q registers.
> Clarify vector arithmetic for d, q registers

- v-spec.adoc
- vector-op-base.csv
This add a destructive integer multiply-add to the spec and the op-types table.
It still needs to be added to encoding table.
> Add Destructive Integer Multiply-Add

- v-spec.adoc
We don't have a vins.v.x instruction, so we can't use it to document the
behavior of vmv.s.x.
> Delete vins.v.x instruction reference.

- v-spec.adoc
Arithmetic instructions don't have a rs2 field.
> Use vs2 not rs2.

- v-spec.adoc
Fixed minor typos in "vsseg3b.v" example.
> Minor typo fix in section 7.8.1

- v-spec.adoc
I didn't change the ones within [source] blocks.
> Use &le; and &ge; instead of <= and >=

- inst-table.adoc
- v-spec.adoc
The vector integer compares were fixed earlier, but the vector float compares were missed.  I also found two missed vector integer compare references in comments.
> Fix compares, changing lte to le and gte to ge.

- v-spec.adoc
Currently, vl=0 is a special case in the spec: elements past vl are left
intact in this case.  vstart >= vl (when vl > 0) is sort of a special case
itself: no elements below vl are updated, but elements past vl are zeroed.
The proposal is to unfiy these cases, and leave the entire vector intact
when vstart >= vl.  Or, put another way, the elements past vl are zeroed if
and only if some other element in the vector needs to be written.
> Unify vl=0 and vstart >= vl rules

- v-spec.adoc
Closes #124
Also, correct the `vfredsum` description to say there are `vl` operations,
not `vl-1`.  The old text correspond to an older variant that did not add
in a scalar element.
> For vfredosum.vs, define that vs1[0] is added first

- v-spec.adoc
These instructions implicitly write the carry-out into v0.  So if rd = v0,
there is a WAW hazard within the instruction itself.  Rather than making the
behavior well defined, which could be annoying to implement for some
microarchitectures but provides little benefit to software, I propose we make
the instructions illegal in this case.
> Disallow rd = v0 for vadc/vsbc

- v-spec.adoc
At least, I think it's a clarification, not a change...
Closes #139
> Clarify that mask instructions operate bitwise within a mask element

- inst-table.adoc
correct sign-injection instruction name in inst-table
> use the same naming for floating sign-injection

- v-spec.adoc
This is a continuation of #133.
> Replace (vl == 0) with (vstart >= vl) in descriptions of permutations

- v-spec.adoc
It should be level 2 '12.13' but not level 3
Signed-off-by: Chih-Min Chao <chihmin.chao@sifive.com>
> fix 12.12.1. Vector Integer Divide Instructions header level

- v-spec.adoc
The existing pseudocode implies that vsbc follows the convention that the carry flag is set if a borrow should occur, but the normative text isn't clear about the polarity.  x86 and SPARC follow this discipline, but ARM and POWER work the other way around.  So we need to be explicit.
> Clarify vsbc carry convention

- inst-table.adoc
- v-spec.adoc
Because it writes a vector register group, not a mask register.
Closes #175
> Rename vmiota.m to viota.m

- inst-table.adoc
- listing.adoc
- v-spec.adoc
- vector-examples.adoc
The destination of Integer/FP comparison instructions is mask
register, so modify related instructions with vm prefixed.
Signed-off-by: Weiwei Wang <weiwei.wangx@outlook.com>
> prefix comparision instructions with vm(#160)

- v-spec.adoc
We instituted the stronger constraint because the instruction previously wrote v0.  Now, the constraint should match masked vector operations.
Motivation is to simplify decoding by removing a special case.
> Weaken constraint that vadc/vsbc can't write v0 to exclude LMUL=1

- v-spec.adoc
This matches the title of the section, and emphasizes that `carry_out` and `borrow_out` do not perform the same operation as each other.
> Consistently use "borrow" rather than "carry" when describing vsbc

- v-spec.adoc
Motivation is to simplify ALU pipeline control for machines that don't take interrupts in the middle of ALU ops.
> Permit implementations to trap vstart values they can't produce

- v-spec.adoc
> Add note about vsetvl with rd=x0; explain why it is useful

- v-spec.adoc
Rationale is similar to that for vmpopc/vmfirst, and avoids need for
a constraint on `vd`.
> Constrain vms*f to require vstart = 0

- v-spec.adoc
A literal reading of the current text would imply it should be signed (as that is the default and vrgather's description says nothing to the contrary), but negative immediates are useless on this instruction, as they would (after sign extension) be larger than 2^31 and thus exceed VLMAX on any implementation and just splat a constant 0 into the destination.
FWIW, binutils currently treats it as unsigned.
> Treat vrgather immediate as unsigned

- v-spec.adoc
1. Treat vrgather scalar register index as unsigned
2. Replace imm with uimm for shift instructions
> follow-up changes from discussion in issue #220

- v-spec.adoc
Since we now describe vmerge and vmv as different instructions, it is clearer
to disentangle their descrptions.  Mention of the fact that they share an
encoding has been moved to a NOTE.
Resolves #238.
> Split merge and move instructions into separate sections

- v-spec.adoc
Some more text is needed to describe the exception model for segmented loads, namely that exceptions are permitted to be imprecise at the sub-structure level.
> Add overlap constraint to vlxseg to support restart

- inst-table.adoc
- v-spec.adoc
This regularizes the integer moves with the floating-point ones, and simplifies the implementation.
The effect of vext.x.v can be obtained with vslidedown.vx followed by vmv.x.s.
Closes #154
> Replace vext.x.v with vmv.x.s

- inst-table.adoc
This encoding needs to examine fewer bits to determine whether an instruction writes x[rd].  It also frees up some encoding space by leveraging the fact that the to-scalar and from-scalar instructions can occupy the same funct6.
The VMUNARY0 opcode is moved to simplify vs1 read-enable decoding.
Resolves #248
> Optimize encoding for instructions that write scalar registers

- inst-table.adoc
- v-spec.adoc
@jhauser-us's survey of the C math library functions concluded that vmford
will not have sufficient impact on performance to justify including.  Many
of the quiet comparisons are against a constant, in which case it does not
help.  For the remaining ones, the penalty is only 1-2 instructions,
depending on whether signaling NaNs are supported.  While signaling NaNs
are supported within the C library itself, GCC's default is to not support
them, so compiled code incurs only a one-instruction penalty for lacking
the vmford instruction.
> Remove the vmford instruction

- v-spec.adoc
> Add note that scalar regs are updated even when vstart >= vl

- v-spec.adoc
Output element i is masked by mask element i, so there are no WAR hazards on the mask register when LMUL=1.
(The Vector Masking section states the weaker LMUL > 1 constraint, so this PR only deletes text.)
Closes #267
> vslideup and vslide1up can overlap the mask register when LMUL=1

- inst-table.adoc
This makes the opcodes consistent with vwmulsu and vmulhsu, in that xxxx10 means vs2 is signed and vs1 is unsigned.
> Swap opcodes of vwmaccsu and vwmaccus

- v-spec.adoc
This matches the extension behavior of vmv.s.x.
> Sign-extend x[rs1] arguments to vslide1up/vslide1down

- v-spec.adoc
> Make carry-in optional for vmadc/vmsbc; re-encode vadc/vsbc accordingly

- v-spec.adoc
This is a straw man for the vector context control field in `mstatus`/`sstatus`.
Sharing the `fcsr` between the F and V extensions makes this a little ugly.  In this proposal, all of `fcsr` is readable and writable when either F or V is available (FS != 0 or VS != 0), and context-switching software is expected to save all of `fcsr` if either FS or VS is Dirty.  It seems a little hacky, but the other solutions seem worse (e.g. requiring both F and V to be enabled to access `fcsr` would pessimize context-switch time for code that only uses the V registers or F registers but not both).
> Add mstatus.VS field

- v-spec.adoc
Since these instructions operate as though SEW=8b, they should perform alignment checks as such.  Machines already need to handle arbitrary alignment for VLE/VSE with SEW=8b, so requiring same for the full-register variants does not impose additional cost.
> Remove ELEN alignment restriction from VL<NF>R/VS<NF>R

- README.md
- some RISC-V V support is now in the master branches
- also reference the PK
> Update links to additional resources in the README

- v-spec.adoc
Otherwise, they can't be reliably used without executing a vsetvl.
> Clarify that vmv<nf>r perform the move even when vstart >= vl

- v-spec.adoc
because VLMAX is defined in terms of `vtype`.
OK, @David-Horner?
> Avoid VLMAX in definition of whole-register instructions

- v-spec.adoc
Remove byte, half and word vector segment loads and stores (including strided and indexed) #354
> Remove non-element vector segment loads and stores to address #354

- v-spec.adoc
If an exception occurs partway through loading a segment, and the mask
register has been overwritten, restarting the load is problematic.
It seems we already came to this conclusion once, beacuse this constraint
exists for indexed segment loads.  The constraint seems to apply equally
to the other classes of segment load, though.
> Add overlap constraint for segment load destination and mask register

- v-spec.adoc
Resolves #380
I added this to the spec in b853d77d9ca539f669960f35d93eed6da9068c1c but @kasanovic reverted it in 01a1adc5274238f103ee1f622d21e735762f916b without explanation, which I think might have been an accident.
The rationale is that, since _output_ element i is masked by mask element i, there is no intra-instruction WAR hazard.
> slide[1]up can overlap the mask if LMUL=1

- .mailmap
- v-spec.adoc
This introduces a `.mailmap` file, which allows correcting the name
and email of past commits without rewriting VCS history. For more
information, see <https://www.git-scm.com/docs/git-check-mailmap>
> Update my name

- v-spec.adoc
- `vmsge{u}.vx vd, va, x, v0.t, vt` can expand into
`vmslt{u}.vx vt, va, x;  vmandnot.mm vd, vd, vt` only if `vd == v0`
- Add expansion for `vmsge{u}.vx vd, va, x, v0.t, vt` for any vd.
```
vmslt{u}.vx vt, va, x
vmandnot.mm vt, v0, vt
vmandnot.mm vd, v0, vd
vmor.mm vd, vt, vd
```
- Derivation process for the instruction sequence:
```
vd[i] = (mask[i] && va[i] >= x) || (!mask[i] && vd[i])
=>
vt[i] = (va[i] < x)
vd[i] = (mask[i] && !vt[i]) || (!mask[i] && vd[i])
=>
vt[i] = (va[i] < x)
vt[i] = (mask[i] && !vt[i])
vd[i] = (!mask[i] && vd[i])
vd[i] = vt[i] || vd[i]
```
> Fix wrong expansion for masked vmsge{u}.vx with temp register

- v-spec.adoc
Since they have EEW=8, making their encoding match that of vle8 avoids a special case.
> Use funct3=0 for vl<nf>r/vs<nf>r

- v-spec.adoc
Allows nodes in the reduction tree to be more precise than required.
Resolves #386.
> Provide more flexibility to vfredsum implementations

- v-spec.adoc
It should be VSSE<EEW> instead of VSE<EEW> for strided store.
> Fix typo for strided store opcodes.

- v-spec.adoc
ELEN < 8 implies a trivial VPU that cannot execute any instructions.
> Clarify ELEN >= 8

- v-spec.adoc
My intent is to constrain indexed loads to disallow index/destination overlap when the index EEW differs from SEW.  AFAICS, indexed loads are the only instructions for which this constraint hasn't been specified. So, making this a blanket constraint, rather than an instruction-specific constraint, is functionally equivalent, but is cleaner IMO.
> Specify overlap constraint for different source/dest EEWs

- calling-convention.adoc
vstart isn't really caller-saved; it's always zero, as far as the calling convention is concerned.
> Improve calling convention description

- v-spec.adoc
The old definition ("vl is reduced to the number of elements processed")
is only true when vstart=0, since elements [0, vstart-1] are not processed.
> Fix definition of first-fault loads w.r.t. nonzero vstart

- v-spec.adoc
Tail elements may be clobbered when vta=1. Clarify this, and avoid the uppercase HINT, which implies that architectural state is not modified.
> vmv.v.v isn't actually a HINT

- v-spec.adoc
... to make it clear we aren't including vector registers used in the scalar context, as with vd in a reduction operation.
> Use "x register" and "f register" instead of "scalar register"

- v-spec.adoc
6dc34f62072a95a4ca1d6dc8d8b43ace731b21ce made what I think was an unintentional change: that the alignment requirement for whole-register loads and stores is min-SEW.  When EEW > min-SEW, this is stricter on implementations than the previous definition, which allowed implementations to require EEW alignment.  The alignment requirement should be on max(EEW, min-SEW).
> Relax whole-register load/store alignment constraints again

- v-spec.adoc
- Make the naming rule consistent with vfncvt.x.f.w.
> Rename vncvt.x.x.v to vncvt.x.x.w

- v-spec.adoc
Commit 7088c9e7 inadvertently changed the constraints for implementations that have SEW_LMUL1MAX_ == SEW_LMUL1MIN_.  The previous expression of the constraint, LMUL >= SEW/ELEN, implicitly (but perhaps esoterically) permitted the set of valid SEWs to vary with the current LMUL setting.  In particular, it was previously valid to set vill when LMUL * ELEN < SEW: e.g., ELEN=64 machines were allowed to reject e16,mf8.
This commit undoes the unintentional change; i.e., it reintroduces the idea that the set of valid SEWs may decrease as fractional LMUL decreases.
> Reintroduce fractional LMUL SEW constraint

- v-spec.adoc
They can change architectural state:
- For vmv.v.v only, tail-agnosticism can alter tail elements
- For both, if vstart was nonzero, it'll become zero
Proposed fix is to use lowercase "hint" instead of RISC-V standard term "HINT".
> vmv.v.v and vmv<nr>r.v aren't truly HINTs

- v-spec.adoc
Reviewed all pseudo instructions for scalar instruction[1], and found fabs are missing for vector.
[1] https://github.com/riscv/riscv-asm-manual/blob/master/riscv-asm.md#a-listing-of-standard-risc-v-pseudoinstructions
> Add assembly pseudoinstructions: vfabs.v

- v-spec.adoc
In the frac lmul section, remind reader that tail elements must obey vta
> Mapping for frac lmul

- v-spec.adoc
Helping readers realize that the equation allows for a simpler choice of just using VLMAX in this case
> Note for readers on vl setting for VLMAX < AVL < 2*VLMAX

- v-spec.adoc
This document mainly uses pseudoinstruction (used 17 times), and this PR proposes eliminating instances of pseudo-instruction (used four times) and pseudo instruction (used four times again) in favor of it. Such has some advantages, including internal consistency and easier indexing (which can help internationalization-related automation).
> Prefer pseudoinstruction over alternatives

- v-spec.adoc
Mask destinations are tail-agnostic, independent of `vta`, in more cases than just "compares": this is stated already in Sec. 3.3.3, as well as in subsequent instruction descriptions.
This PR mitigates the inconsistency but aggravates the redundancy.
> Clarify (redundant) statement about vta

- v-spec.adoc
It's true that vasub can never overflow when rounding down or jamming, but when rounding to nearest and using the most extreme operands, overflow _can_ occur.
> Fix incorrect statement about vasub overflow

- v-spec.adoc
The old text points out that, because the in-memory layout and in-register layouts are the same, the instructions behave the same as moving vectors of bytes with EEW=8.  True enough as far as the data transfer, but not so for the handling of evl/vstart: those actually do depend on the encoded EEW.
This choice is consistent with the later statement that "implementations are allowed to raise a misaligned address exception on whole register loads", meaning (a) that EEW is not truly a HINT and (b) the unit of transfer really is elements, not bytes, even if the effect of a successful transfer is the same.
Fix by rewriting misleading text and moving it to non-normative.
> Clarify that whole-register loads do use the encoded EEW

- v-spec.adoc
I guess this is technically a semantic change, not a clarification, but I believe it is what @kasanovic intended in writing "vector mask logical instructions are always unmasked".
Resolves #686
> vm=0 encodings should be reserved for mask-logical instructions

- ediv.adoc
- example/memcpy.s
- example/saxpy.s
- example/strcpy.s
- example/strlen.s
- example/strncpy.s
- example/vvaddint32.s
- v-spec.adoc
- vector-examples.adoc
It should have spaces between assembly operands for readability.
Comments for example code doesn't be realigned.
I think all of comments alignment can be unified by other commit.
> Add space between VType's operands

- v-spec.adoc
I believe that the following commentary is incorrect:
> Any use of the vector unit will require an initial `vset{i}vl{i}`,which will reset `vstart`. 
For example, whole-register operations (copies/loads/stores) can be invoked without `vset{i}vl{i}`. Indeed, we (SiFive) have encountered real application codes generated by LLVM (using RVV intrinsics) which do just this.
This PR only affects non-normative text, i.e., it does not change the specification.
> vstart needs explicit initialization by software at reset

- v-spec.adoc
This is a generalization of fd4565e18d882d3ad2df8592be81034bafac1b71 in response to @JamesKenneyImperas' comment https://github.com/riscv/riscv-v-spec/commit/fd4565e18d882d3ad2df8592be81034bafac1b71#commitcomment-51940463
> Further relax tail handling for mask logical instructions

- example/strncpy.s
The pointer arithmetics originally exist after the branch instruction. So they
will be omitted when n is greater than length of src, and the setting of zero
tails will not match the real strncmp.
> Fix implementation of strncpy

- v-spec.adoc
Due to what appears to be an editing error in 9c83a0176664bb1fd6ba5b58d14cc80a7563868f, the definition of v[f]slide1down wasn't changed to respect the mask agnostic/undisturbed policy for elt. vl-1.  It should've been.
h/t Brandon Wu
> v[f]slide1down respects the mask policy

- vector-examples.adoc
As @aswaterman mentioned in https://github.com/riscv/riscv-v-spec/issues/793, the previous example for square root approximation fails when the input is the smallest subnormal float.  This PR fixes that case by avoiding the multiplication by `0.5` that produces a NaN, albeit at the cost of an extra multiply per refinement step.
> Fix sqrt approx for smallest subnormal

- v-spec.adoc
RVTSO applies to all vector memory instructions at the instruction level, but RVWMO still applies at the intra-instruction level.
> Define RVV-RVTSO bindings

- v-spec.adoc
Fix example's typo "vluxseg3ei32.v" to "vluxseg3ei8.v" in section 7.8.3.
> Fix typo in section 7.8.3.

- v-spec.adoc
Added policies to examples I could find that were not updated.
Did not touch `ediv.adoc` which still has some missing ones, but I understand that one will have major changes anyways.
Tail-agnostic/mask-agnostic as is the suggested default
> Specify tail/mask policy in vsetvli examples

- v-spec.adoc
Vector instructions that process IEEE 754 binary16 numbers were included in draft versions of the vector extension, but they were separated from the V extension prior to ratification.  This PR adds them back.
The Zvfh extension adds IEEE 754 binary16 support to all FP instructions.
The Zvfhmin extension adds only the conversions to and from binary32.
> Add draft Zvfh and Zvfhmin specs

- v-spec.adoc
For consistency with the unprivileged ISA spec, use the verb "depend" to say that an extension requires and implies another.
Explicitly state the dependence between V and Zve*.
Resolves #844
> Clarify dependencies between ISA extensions

- v-spec.adoc
I think it could make reader aware that "The remaining elements of vd are treated as tail elements according to the current tail policy"
> Add vsetvli to indicate vl and policy in vcompress example.

- v-spec.adoc
It's not meaningful to restrict vstart values on the basis of SEW alone, as the maximum element index is a function of LMUL, as well.
> Fix description of reserved vstart values

- v-spec.adoc
Following discussion with @aswaterman: suggestion of clarification for `vf[w]redusum.vs` instruction behavior when it comes to `fflags`: mentioning that each operator node and conversion will raise floating-point exception flags when appropriate (invalid operation would not directly originate from the conversion operation, inexact, overflow, underflow would).
Signed-off-by: Nicolas Brunie <82109999+nibrunieAtSi5@users.noreply.github.com>
> Suggesting clarification for unordered red  flags

- vcfg-format.adoc
Signed-off-by: Nicolas Brunie <82109999+nibrunieAtSi5@users.noreply.github.com>
It looks like func7 field (bits: 1 + bits: 6) is too long and does not hold the correct value here
> Suggestion for Fixing func7 for vsetvl

- vcfg-format.adoc
This matches how the vset(i)vli instructions are defined.
I'm not sure what the 'z' in zimm was meant to convey. The base ISA spec uses nzimm to mean an immediate that can't be zero, but I don't think it ever uses zimm.
Signed-off-by: Craig Topper <craig.topper@gmail.com>
> Use vtypei instead of zimm in vcfg-format.adoc

- v-spec.adoc
Closes #867 .
Another option is to make this clarification earlier. I don't have strong feelings. Someone else is welcome to propose that.
> Clarify EMUL constraint for indexed segment ops

- v-spec.adoc
I found a grammatical mistake in `Vector Strided Instructions` section. This is fixed in this PR.
> Fix typo in a note

- v-spec.adoc
The normative text says that vmv&lt;nr&gt;r.v "operates as though EEW=SEW", meaning that it _does_ depend on vtype.
The semantic difference becomes visible through vstart, since vstart is measured in elements; hence, how to set vstart on an interrupt, or interpret vstart upon resumption, depends on vtype.
> Delete non-normative claim that vmv<nr>r.v doesn't depend on vtype

- README.md
- package.json
- v-spec.adoc
This PR makes minor cosmetic changes and updates NodeJS and datasheet.js
requirements to build with `npm run build`. I could not build with Node v6, but
found that Node v18 worked out. Node v20 works fine, too. I also had to run
`npm audit fix --force` (which force-updated `datasheet`) and
`npm rebuild canvas` when switching between Node versions.
> A few minor fixes

- element_groups.adoc
EGS > VLMAX is illegal.  However, vl being indivisible by EGS is merely reserved.
This design preserves the most important error checking (of code that assumes VLEN is larger than it actually is) but simplifies implementations that do not know vl early in the pipeline.
> Update element group illegal-inst behavior to match vector crypto

- v-spec.adoc
The `vlm`/`vsm` instructions are only meant to be used when `vill`=0, since they are designed to spill or fill only the active subset of a mask register, rather than a whole register.
Recently, the argument was made that they don't truly depend on `vtype`, since their behavior does not depend on the `vma`, `vta`, `vsew`, or `vlmul` fields.  However, the instructions are obviously useless when `vill`=1, since `vill`=1 implies `vl`=0, and so the instructions would become NOPs.
My take is that the instructions indirectly depend on `vtype`, since the instructions depend on `vl`, and `vtype` governs the set of values `vl` may assume. It's not clear that my reasoning is ironclad, but I do believe it to be in line with what the spec authors intended.
> "Clarify" that vlm/vsm respect vtype.vill

- v-spec.adoc
This PR clarifies that masked compares AND in the mask only if the destination register is `v0`, as discussed in #900
> Clarify that compares only AND in the mask if vd == v0

- v-spec.adoc
Since `V/Zve*/Zvl*` and `Zfinx/Zdinx/Zhinx` extensions are ratified, we no longer need the word "proposed" or references to the public review.
But if you know a better sentence describing the list of vector extensions (near line 4978-4979), please notify me (as a non-native speaker, I always have such anxiety).
> Specification status updates

- v-spec.adoc
Shouldn't the lower bound for `i` and unchanged behavior be `0` included rather than excluded ?
If OFFSET is 1
```
vd[0] is unchanged
vd[1] is vs2[0] if v0.mask[i] enabled
...
```
> vslide unchanged range correction
